default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username:
  password:
  pool: 10

development:
  <<: *default
  database: rewards_server_development

test:
  <<: *default
  database: rewards_server_test

staging:
  <<: *default
  database: rewards_server_staging

production:
  <<: *default
  database: rewards_server_production
  pool: <%= ENV['MAX_THREADS'] || 25 %>
